import type { PilotFoodCategory, PilotPreparationExpectation } from "../../src/lib/usda/catalog-pilot";

export interface CatalogDiscoveryTarget {
  id: string;
  target: string;
  query: string;
  category: PilotFoodCategory;
  preparationExpectation: PilotPreparationExpectation;
  preferredDataTypes: string[];
  suggestedAliases: string[];
}

export interface CatalogTargetBatch {
  batchId: string;
  label: string;
  targets: CatalogDiscoveryTarget[];
}

const COMMON_PREFERRED_DATA_TYPES = ["Foundation", "Survey (FNDDS)", "SR Legacy"];

function t(input: Omit<CatalogDiscoveryTarget, "preferredDataTypes">): CatalogDiscoveryTarget {
  return {
    ...input,
    preferredDataTypes: COMMON_PREFERRED_DATA_TYPES,
  };
}

export const CATALOG_TARGET_BATCHES: CatalogTargetBatch[] = [
  {
    batchId: "batch-01-poultry-eggs",
    label: "Poultry and eggs expansion",
    targets: [
      t({
        id: "protein_chicken_breast_cooked_grilled",
        target: "Chicken breast, skinless, boneless, cooked, grilled",
        query: "chicken breast skinless boneless meat only cooked grilled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["chicken breast grilled", "grilled chicken breast", "skinless chicken breast grilled"],
      }),
      t({
        id: "protein_chicken_breast_cooked_roasted",
        target: "Chicken breast, meat only, cooked, roasted",
        query: "chicken breast meat only cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["chicken breast roasted", "roasted chicken breast", "breast meat roasted"],
      }),
      t({
        id: "protein_chicken_thigh_raw_skin_on",
        target: "Chicken thigh, meat and skin, raw",
        query: "chicken thigh meat and skin raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["chicken thigh skin on raw", "raw chicken thigh skin on", "thigh meat skin raw"],
      }),
      t({
        id: "protein_chicken_thigh_cooked_skin_on",
        target: "Chicken thigh, meat and skin, cooked, roasted",
        query: "chicken thigh meat and skin cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["chicken thigh skin on cooked", "roasted chicken thigh skin on", "thigh meat skin roasted"],
      }),
      t({
        id: "protein_chicken_drumstick_raw",
        target: "Chicken drumstick, meat and skin, raw",
        query: "chicken drumstick meat and skin raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["chicken drumstick raw", "raw chicken drumstick", "drumstick raw skin on"],
      }),
      t({
        id: "protein_chicken_drumstick_cooked",
        target: "Chicken drumstick, meat and skin, cooked, roasted",
        query: "chicken drumstick meat and skin cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["chicken drumstick roasted", "roasted chicken drumstick", "drumstick cooked skin on"],
      }),
      t({
        id: "protein_chicken_wing_raw",
        target: "Chicken wing, meat and skin, raw",
        query: "chicken wing meat and skin raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["chicken wing raw", "raw chicken wing", "wing raw skin on"],
      }),
      t({
        id: "protein_chicken_wing_cooked",
        target: "Chicken wing, meat and skin, cooked, roasted",
        query: "chicken wing meat and skin cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["chicken wing roasted", "roasted chicken wing", "wing cooked skin on"],
      }),
      t({
        id: "protein_ground_chicken_raw",
        target: "Ground chicken, raw",
        query: "chicken ground raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["ground chicken raw", "raw ground chicken", "chicken mince raw"],
      }),
      t({
        id: "protein_ground_chicken_cooked",
        target: "Ground chicken, cooked",
        query: "chicken ground cooked",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["ground chicken cooked", "cooked ground chicken", "chicken mince cooked"],
      }),
      t({
        id: "protein_turkey_breast_raw",
        target: "Turkey breast, meat only, raw",
        query: "turkey breast meat only raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["turkey breast raw", "raw turkey breast", "turkey breast meat raw"],
      }),
      t({
        id: "protein_turkey_breast_cooked",
        target: "Turkey breast, meat only, cooked, roasted",
        query: "turkey breast meat only cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["turkey breast roasted", "roasted turkey breast", "turkey breast cooked"],
      }),
      t({
        id: "protein_turkey_thigh_raw",
        target: "Turkey thigh, meat only, raw",
        query: "turkey thigh meat only raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["turkey thigh raw", "raw turkey thigh", "turkey thigh meat raw"],
      }),
      t({
        id: "protein_turkey_thigh_cooked",
        target: "Turkey thigh, meat only, cooked, roasted",
        query: "turkey thigh meat only cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["turkey thigh roasted", "roasted turkey thigh", "turkey thigh cooked"],
      }),
      t({
        id: "protein_ground_turkey_93_raw",
        target: "Ground turkey, 93% lean / 7% fat, raw",
        query: "ground turkey 93% lean 7% fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["ground turkey 93 7 raw", "93 lean ground turkey raw", "turkey mince 93 7 raw"],
      }),
      t({
        id: "protein_ground_turkey_93_cooked",
        target: "Ground turkey, 93% lean / 7% fat, cooked",
        query: "ground turkey 93% lean 7% fat cooked",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["ground turkey 93 7 cooked", "93 lean ground turkey cooked", "turkey mince 93 7 cooked"],
      }),
      t({
        id: "protein_ground_turkey_85_raw",
        target: "Ground turkey, 85% lean / 15% fat, raw",
        query: "ground turkey 85% lean 15% fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["ground turkey 85 15 raw", "85 lean ground turkey raw", "turkey mince 85 15 raw"],
      }),
      t({
        id: "protein_ground_turkey_85_cooked",
        target: "Ground turkey, 85% lean / 15% fat, cooked",
        query: "ground turkey 85% lean 15% fat cooked",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["ground turkey 85 15 cooked", "85 lean ground turkey cooked", "turkey mince 85 15 cooked"],
      }),
      t({
        id: "protein_egg_whole_hard_boiled",
        target: "Egg, whole, hard-boiled",
        query: "egg whole cooked hard boiled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["hard boiled egg", "boiled whole egg", "egg whole boiled"],
      }),
      t({
        id: "protein_egg_whole_scrambled",
        target: "Egg, whole, scrambled",
        query: "egg whole cooked scrambled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["scrambled egg", "scrambled whole egg", "egg scramble cooked"],
      }),
      t({
        id: "protein_egg_white_cooked",
        target: "Egg white, cooked",
        query: "egg white cooked",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["cooked egg white", "egg whites cooked", "egg white heated"],
      }),
      t({
        id: "protein_egg_whole_fried",
        target: "Egg, whole, fried",
        query: "egg whole fried",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["fried egg", "egg fried whole", "whole egg fried"],
      }),
      t({
        id: "protein_egg_omelet_plain",
        target: "Omelet, plain, whole egg",
        query: "omelet plain egg",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["plain omelet", "egg omelet plain", "omelette plain egg"],
      }),
    ],
  },
  {
    batchId: "batch-02-beef-pork",
    label: "Beef and pork expansion",
    targets: [
      t({
        id: "protein_ground_beef_80_raw",
        target: "Ground beef, 80% lean / 20% fat, raw",
        query: "beef ground 80% lean 20% fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["ground beef 80 20 raw", "80 lean ground beef raw", "beef mince 80 20 raw"],
      }),
      t({
        id: "protein_ground_beef_80_cooked",
        target: "Ground beef, 80% lean / 20% fat, cooked patty",
        query: "beef ground 80% lean 20% fat patty cooked broiled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["ground beef 80 20 cooked", "80 lean ground beef cooked", "beef patty 80 20 cooked"],
      }),
      t({
        id: "protein_ground_beef_85_raw",
        target: "Ground beef, 85% lean / 15% fat, raw",
        query: "beef ground 85% lean 15% fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["ground beef 85 15 raw", "85 lean ground beef raw", "beef mince 85 15 raw"],
      }),
      t({
        id: "protein_ground_beef_85_cooked",
        target: "Ground beef, 85% lean / 15% fat, cooked patty",
        query: "beef ground 85% lean 15% fat patty cooked broiled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["ground beef 85 15 cooked", "85 lean ground beef cooked", "beef patty 85 15 cooked"],
      }),
      t({
        id: "protein_ground_beef_93_raw",
        target: "Ground beef, 93% lean / 7% fat, raw",
        query: "beef ground 93% lean 7% fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["ground beef 93 7 raw", "93 lean ground beef raw", "beef mince 93 7 raw"],
      }),
      t({
        id: "protein_ground_beef_93_cooked",
        target: "Ground beef, 93% lean / 7% fat, cooked patty",
        query: "beef ground 93% lean 7% fat patty cooked broiled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["ground beef 93 7 cooked", "93 lean ground beef cooked", "beef patty 93 7 cooked"],
      }),
      t({
        id: "protein_ground_beef_95_raw",
        target: "Ground beef, 95% lean / 5% fat, raw",
        query: "beef ground 95% lean 5% fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["ground beef 95 5 raw", "95 lean ground beef raw", "beef mince 95 5 raw"],
      }),
      t({
        id: "protein_ground_beef_95_cooked",
        target: "Ground beef, 95% lean / 5% fat, cooked patty",
        query: "beef ground 95% lean 5% fat patty cooked broiled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["ground beef 95 5 cooked", "95 lean ground beef cooked", "beef patty 95 5 cooked"],
      }),
      t({
        id: "protein_beef_sirloin_raw",
        target: "Beef sirloin, lean only, raw",
        query: "beef top sirloin separable lean only trimmed to 0 fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["sirloin raw", "beef sirloin raw", "top sirloin raw lean"],
      }),
      t({
        id: "protein_beef_sirloin_cooked",
        target: "Beef sirloin, lean only, cooked",
        query: "beef top sirloin separable lean only trimmed to 0 fat cooked broiled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["sirloin cooked", "beef sirloin cooked", "top sirloin broiled"],
      }),
      t({
        id: "protein_beef_tenderloin_raw",
        target: "Beef tenderloin, lean only, raw",
        query: "beef tenderloin separable lean only trimmed to 0 fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["tenderloin raw", "beef tenderloin raw", "filet raw lean"],
      }),
      t({
        id: "protein_beef_tenderloin_cooked",
        target: "Beef tenderloin, lean only, cooked",
        query: "beef tenderloin separable lean only trimmed to 0 fat cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["tenderloin cooked", "beef tenderloin cooked", "filet roasted lean"],
      }),
      t({
        id: "protein_beef_flank_raw",
        target: "Beef flank steak, lean only, raw",
        query: "beef flank steak separable lean only raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["flank steak raw", "beef flank raw", "flank raw lean"],
      }),
      t({
        id: "protein_beef_flank_cooked",
        target: "Beef flank steak, lean only, cooked",
        query: "beef flank steak separable lean only cooked broiled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["flank steak cooked", "beef flank cooked", "flank broiled lean"],
      }),
      t({
        id: "protein_beef_chuck_raw",
        target: "Beef chuck, lean only, raw",
        query: "beef chuck shoulder roast separable lean only trimmed to 0 fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["beef chuck raw", "chuck roast raw", "chuck lean raw"],
      }),
      t({
        id: "protein_beef_chuck_cooked",
        target: "Beef chuck, lean only, cooked",
        query: "beef chuck shoulder roast separable lean only cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["beef chuck cooked", "chuck roast cooked", "chuck lean roasted"],
      }),
      t({
        id: "protein_beef_round_raw",
        target: "Beef round, lean only, raw",
        query: "beef round top round separable lean only trimmed to 0 fat raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["beef round raw", "top round raw", "round lean raw"],
      }),
      t({
        id: "protein_beef_round_cooked",
        target: "Beef round, lean only, cooked",
        query: "beef round top round separable lean only cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["beef round cooked", "top round cooked", "round lean roasted"],
      }),
      t({
        id: "protein_pork_tenderloin_raw",
        target: "Pork tenderloin, lean only, raw",
        query: "pork fresh loin tenderloin separable lean only raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["pork tenderloin raw", "raw pork tenderloin", "pork loin tenderloin raw"],
      }),
      t({
        id: "protein_pork_tenderloin_cooked",
        target: "Pork tenderloin, lean only, cooked",
        query: "pork fresh loin tenderloin separable lean only cooked roasted",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["pork tenderloin cooked", "roasted pork tenderloin", "pork tenderloin roasted"],
      }),
      t({
        id: "protein_pork_loin_raw",
        target: "Pork loin chop, lean only, raw",
        query: "pork fresh loin center loin chop separable lean only raw",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["pork loin raw", "pork chop raw lean", "loin chop raw"],
      }),
      t({
        id: "protein_pork_loin_cooked",
        target: "Pork loin chop, lean only, cooked",
        query: "pork fresh loin center loin chop separable lean only cooked broiled",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["pork loin cooked", "pork chop cooked lean", "loin chop broiled"],
      }),
      t({
        id: "protein_pork_chop_raw",
        target: "Pork chop, meat and fat, raw",
        query: "pork loin chop raw meat and fat",
        category: "protein",
        preparationExpectation: "raw",
        suggestedAliases: ["pork chop raw", "raw pork chop", "pork chop meat fat raw"],
      }),
      t({
        id: "protein_pork_chop_cooked",
        target: "Pork chop, meat and fat, cooked",
        query: "pork loin chop cooked broiled meat and fat",
        category: "protein",
        preparationExpectation: "cooked",
        suggestedAliases: ["pork chop cooked", "broiled pork chop", "pork chop meat fat cooked"],
      }),
    ],
  },
  {
    batchId: "batch-03-seafood",
    label: "Seafood expansion",
    targets: [
      t({
        id: "seafood_salmon_atlantic_wild_raw",
        target: "Salmon, Atlantic, wild, raw",
        query: "fish salmon atlantic wild raw",
        category: "seafood",
        preparationExpectation: "raw",
        suggestedAliases: ["salmon wild raw", "atlantic wild salmon raw", "raw salmon wild"],
      }),
      t({
        id: "seafood_salmon_atlantic_farmed_raw",
        target: "Salmon, Atlantic, farmed, raw",
        query: "fish salmon atlantic farmed raw",
        category: "seafood",
        preparationExpectation: "raw",
        suggestedAliases: ["salmon farmed raw", "atlantic farmed salmon raw", "raw salmon farmed"],
      }),
      t({
        id: "seafood_salmon_atlantic_farmed_cooked",
        target: "Salmon, Atlantic, farmed, cooked, dry heat",
        query: "fish salmon atlantic farmed cooked dry heat",
        category: "seafood",
        preparationExpectation: "cooked",
        suggestedAliases: ["salmon farmed cooked", "atlantic farmed salmon cooked", "salmon dry heat farmed"],
      }),
      t({
        id: "seafood_salmon_sockeye_raw",
        target: "Salmon, sockeye, raw",
        query: "fish salmon sockeye raw",
        category: "seafood",
        preparationExpectation: "raw",
        suggestedAliases: ["sockeye salmon raw", "raw sockeye salmon", "salmon sockeye raw"],
      }),
      t({
        id: "seafood_salmon_sockeye_cooked",
        target: "Salmon, sockeye, cooked, dry heat",
        query: "fish salmon sockeye cooked dry heat",
        category: "seafood",
        preparationExpectation: "cooked",
        suggestedAliases: ["sockeye salmon cooked", "cooked sockeye salmon", "salmon sockeye cooked"],
      }),
      t({
        id: "seafood_tilapia_raw",
        target: "Tilapia, raw",
        query: "fish tilapia raw",
        category: "seafood",
        preparationExpectation: "raw",
        suggestedAliases: ["tilapia raw", "raw tilapia", "fish tilapia raw"],
      }),
      t({
        id: "seafood_cod_raw",
        target: "Cod, Atlantic, raw",
        query: "fish cod atlantic raw",
        category: "seafood",
        preparationExpectation: "raw",
        suggestedAliases: ["cod raw", "atlantic cod raw", "raw cod fish"],
      }),
      t({
        id: "seafood_cod_cooked",
        target: "Cod, Atlantic, cooked, dry heat",
        query: "fish cod atlantic cooked dry heat",
        category: "seafood",
        preparationExpectation: "cooked",
        suggestedAliases: ["cod cooked", "atlantic cod cooked", "cod dry heat"],
      }),
      t({
        id: "seafood_tuna_yellowfin_raw",
        target: "Tuna, yellowfin, raw",
        query: "fish tuna yellowfin raw",
        category: "seafood",
        preparationExpectation: "raw",
        suggestedAliases: ["yellowfin tuna raw", "raw yellowfin tuna", "tuna raw yellowfin"],
      }),
      t({
        id: "seafood_tuna_yellowfin_cooked",
        target: "Tuna, yellowfin, cooked, dry heat",
        query: "fish tuna yellowfin cooked dry heat",
        category: "seafood",
        preparationExpectation: "cooked",
        suggestedAliases: ["yellowfin tuna cooked", "cooked yellowfin tuna", "tuna yellowfin cooked"],
      }),
      t({
        id: "seafood_tuna_light_canned_water",
        target: "Tuna, light, canned in water, drained solids",
        query: "tuna light canned in water drained solids",
        category: "seafood",
        preparationExpectation: "neutral",
        suggestedAliases: ["canned tuna water", "tuna canned water drained", "light tuna canned water"],
      }),
      t({
        id: "seafood_tuna_white_canned_water",
        target: "Tuna, white, canned in water, drained solids",
        query: "tuna white canned in water drained solids",
        category: "seafood",
        preparationExpectation: "neutral",
        suggestedAliases: ["albacore canned tuna water", "white tuna canned water", "canned white tuna"],
      }),
      t({
        id: "seafood_shrimp_raw",
        target: "Shrimp, mixed species, raw",
        query: "shrimp mixed species raw",
        category: "seafood",
        preparationExpectation: "raw",
        suggestedAliases: ["shrimp raw", "raw shrimp", "mixed shrimp raw"],
      }),
      t({
        id: "seafood_shrimp_cooked",
        target: "Shrimp, mixed species, cooked",
        query: "shrimp mixed species cooked",
        category: "seafood",
        preparationExpectation: "cooked",
        suggestedAliases: ["shrimp cooked", "cooked shrimp", "mixed shrimp cooked"],
      }),
      t({
        id: "seafood_crab_raw",
        target: "Crab, blue crab, raw",
        query: "crab blue crab raw",
        category: "seafood",
        preparationExpectation: "raw",
        suggestedAliases: ["crab raw", "blue crab raw", "raw crab"],
      }),
      t({
        id: "seafood_crab_cooked",
        target: "Crab, blue crab, cooked, moist heat",
        query: "crab blue crab cooked moist heat",
        category: "seafood",
        preparationExpectation: "cooked",
        suggestedAliases: ["crab cooked", "blue crab cooked", "crab moist heat"],
      }),
      t({
        id: "seafood_sardines_canned_oil",
        target: "Sardines, canned in oil, drained solids",
        query: "sardines canned in oil drained solids with bone",
        category: "seafood",
        preparationExpectation: "neutral",
        suggestedAliases: ["sardines canned oil", "canned sardines oil", "sardine drained oil"],
      }),
      t({
        id: "seafood_mackerel_cooked",
        target: "Mackerel, Atlantic, cooked, dry heat",
        query: "fish mackerel atlantic cooked dry heat",
        category: "seafood",
        preparationExpectation: "cooked",
        suggestedAliases: ["mackerel cooked", "atlantic mackerel cooked", "mackerel dry heat"],
      }),
      t({
        id: "seafood_halibut_cooked",
        target: "Halibut, Atlantic and Pacific, cooked, dry heat",
        query: "fish halibut atlantic pacific cooked dry heat",
        category: "seafood",
        preparationExpectation: "cooked",
        suggestedAliases: ["halibut cooked", "cooked halibut", "halibut dry heat"],
      }),
      t({
        id: "seafood_pollock_cooked",
        target: "Pollock, Atlantic, cooked, dry heat",
        query: "fish pollock atlantic cooked dry heat",
        category: "seafood",
        preparationExpectation: "cooked",
        suggestedAliases: ["pollock cooked", "atlantic pollock cooked", "pollock dry heat"],
      }),
    ],
  },
  {
    batchId: "batch-04-grains-starches",
    label: "Grains, starches, legumes, breads",
    targets: [
      t({
        id: "grain_white_rice_medium_cooked",
        target: "White rice, medium-grain, cooked",
        query: "rice white medium grain enriched cooked",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["white rice medium cooked", "medium grain white rice cooked", "rice medium cooked"],
      }),
      t({
        id: "grain_white_rice_short_cooked",
        target: "White rice, short-grain, cooked",
        query: "rice white short grain enriched cooked",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["white rice short cooked", "short grain white rice cooked", "rice short cooked"],
      }),
      t({
        id: "grain_white_rice_parboiled_cooked",
        target: "White rice, long-grain, parboiled, cooked",
        query: "rice white long grain parboiled cooked",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["parboiled white rice cooked", "white rice parboiled cooked", "long grain parboiled rice"],
      }),
      t({
        id: "grain_brown_rice_long_cooked",
        target: "Brown rice, long-grain, cooked",
        query: "rice brown long grain cooked",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["brown rice long grain cooked", "long grain brown rice cooked", "brown rice cooked"],
      }),
      t({
        id: "grain_wild_rice_cooked",
        target: "Wild rice, cooked",
        query: "wild rice cooked",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["wild rice cooked", "cooked wild rice", "rice wild cooked"],
      }),
      t({
        id: "grain_oatmeal_cooked_water",
        target: "Oatmeal, regular and quick, cooked with water",
        query: "cereals oats regular quick cooked with water",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["oatmeal cooked water", "cooked oats water", "oats cooked plain"],
      }),
      t({
        id: "grain_oats_instant_dry",
        target: "Oats, instant, plain, dry",
        query: "cereals oats instant fortified plain dry",
        category: "grains_and_starches",
        preparationExpectation: "neutral",
        suggestedAliases: ["instant oats dry", "oats instant dry", "plain instant oats dry"],
      }),
      t({
        id: "grain_quinoa_cooked",
        target: "Quinoa, cooked",
        query: "quinoa cooked",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["quinoa cooked", "cooked quinoa", "quinoa boiled"],
      }),
      t({
        id: "grain_pasta_spaghetti_cooked",
        target: "Pasta, spaghetti, cooked",
        query: "pasta spaghetti cooked enriched",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["spaghetti cooked", "cooked spaghetti", "pasta spaghetti cooked"],
      }),
      t({
        id: "grain_pasta_macaroni_cooked",
        target: "Pasta, macaroni, cooked",
        query: "pasta macaroni cooked enriched",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["macaroni cooked", "cooked macaroni", "pasta macaroni cooked"],
      }),
      t({
        id: "grain_pasta_whole_wheat_cooked",
        target: "Pasta, whole-wheat, cooked",
        query: "pasta whole wheat cooked",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["whole wheat pasta cooked", "cooked whole wheat pasta", "wheat pasta cooked"],
      }),
      t({
        id: "grain_potato_boiled_no_salt",
        target: "Potato, boiled, drained, without salt",
        query: "potatoes boiled cooked without salt",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["potato boiled", "boiled potato no salt", "potatoes boiled plain"],
      }),
      t({
        id: "grain_potato_mashed_milk_butter",
        target: "Potatoes, mashed, with milk and butter",
        query: "potatoes mashed home prepared whole milk butter added",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["mashed potatoes", "potato mash", "mashed potato milk butter"],
      }),
      t({
        id: "grain_sweet_potato_boiled",
        target: "Sweet potato, boiled, cooked, without skin",
        query: "sweet potato cooked boiled without skin",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["sweet potato boiled", "boiled sweet potato", "sweet potato cooked boiled"],
      }),
      t({
        id: "grain_black_beans_cooked",
        target: "Black beans, mature seeds, cooked",
        query: "beans black mature seeds cooked boiled without salt",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["black beans cooked", "cooked black beans", "black beans boiled"],
      }),
      t({
        id: "grain_kidney_beans_cooked",
        target: "Kidney beans, mature seeds, cooked",
        query: "beans kidney red mature seeds cooked boiled without salt",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["kidney beans cooked", "cooked kidney beans", "red kidney beans cooked"],
      }),
      t({
        id: "grain_pinto_beans_cooked",
        target: "Pinto beans, mature seeds, cooked",
        query: "beans pinto mature seeds cooked boiled without salt",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["pinto beans cooked", "cooked pinto beans", "pinto beans boiled"],
      }),
      t({
        id: "grain_chickpeas_cooked",
        target: "Chickpeas, mature seeds, cooked",
        query: "chickpeas garbanzo beans mature seeds cooked boiled without salt",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["chickpeas cooked", "garbanzo beans cooked", "cooked chickpeas"],
      }),
      t({
        id: "grain_lentils_cooked",
        target: "Lentils, mature seeds, cooked",
        query: "lentils mature seeds cooked boiled without salt",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["lentils cooked", "cooked lentils", "lentils boiled"],
      }),
      t({
        id: "grain_green_peas_cooked",
        target: "Peas, green, cooked, boiled, drained, without salt",
        query: "peas green cooked boiled drained without salt",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["green peas cooked", "cooked peas", "peas boiled no salt"],
      }),
      t({
        id: "grain_corn_sweet_yellow_cooked",
        target: "Corn, sweet, yellow, cooked",
        query: "corn sweet yellow cooked boiled drained without salt",
        category: "grains_and_starches",
        preparationExpectation: "cooked",
        suggestedAliases: ["corn cooked", "sweet corn cooked", "yellow corn cooked"],
      }),
      t({
        id: "grain_bread_white",
        target: "Bread, white",
        query: "bread white commercially prepared",
        category: "grains_and_starches",
        preparationExpectation: "neutral",
        suggestedAliases: ["white bread", "bread white", "sandwich bread white"],
      }),
      t({
        id: "grain_bread_whole_wheat",
        target: "Bread, whole-wheat",
        query: "bread whole wheat commercially prepared",
        category: "grains_and_starches",
        preparationExpectation: "neutral",
        suggestedAliases: ["whole wheat bread", "wheat bread", "bread whole wheat"],
      }),
      t({
        id: "grain_tortilla_corn",
        target: "Tortilla, corn",
        query: "tortillas ready to bake or fry corn",
        category: "grains_and_starches",
        preparationExpectation: "neutral",
        suggestedAliases: ["corn tortilla", "tortilla corn", "corn tortillas"],
      }),
      t({
        id: "grain_tortilla_flour",
        target: "Tortilla, flour",
        query: "tortilla plain flour ready to bake or fry",
        category: "grains_and_starches",
        preparationExpectation: "neutral",
        suggestedAliases: ["flour tortilla", "tortilla flour", "flour tortillas"],
      }),
      t({
        id: "grain_bagel_plain",
        target: "Bagel, plain",
        query: "bagels plain enriched with calcium propionate includes onion poppy sesame",
        category: "grains_and_starches",
        preparationExpectation: "neutral",
        suggestedAliases: ["plain bagel", "bagel plain", "bagels plain"],
      }),
    ],
  },
  {
    batchId: "batch-05-dairy",
    label: "Dairy expansion",
    targets: [
      t({
        id: "dairy_milk_2_percent",
        target: "Milk, reduced fat, 2% milkfat",
        query: "milk reduced fat fluid 2% milkfat with added vitamin a and vitamin d",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["milk 2 percent", "2% milk", "reduced fat milk 2%"],
      }),
      t({
        id: "dairy_milk_1_percent",
        target: "Milk, lowfat, 1% milkfat",
        query: "milk lowfat fluid 1% milkfat with added vitamin a and vitamin d",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["milk 1 percent", "1% milk", "lowfat milk 1%"],
      }),
      t({
        id: "dairy_milk_nonfat",
        target: "Milk, nonfat, skim",
        query: "milk nonfat fluid with added vitamin a and vitamin d",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["skim milk", "nonfat milk", "fat free milk"],
      }),
      t({
        id: "dairy_greek_yogurt_lowfat",
        target: "Yogurt, Greek, plain, lowfat",
        query: "yogurt greek plain lowfat",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["greek yogurt lowfat plain", "lowfat greek yogurt", "greek plain lowfat"],
      }),
      t({
        id: "dairy_greek_yogurt_whole",
        target: "Yogurt, Greek, plain, whole milk",
        query: "yogurt greek plain whole milk",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["greek yogurt whole plain", "whole milk greek yogurt", "greek plain whole"],
      }),
      t({
        id: "dairy_yogurt_plain_whole",
        target: "Yogurt, plain, whole milk",
        query: "yogurt plain whole milk",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["plain yogurt whole", "whole milk yogurt plain", "regular yogurt whole"],
      }),
      t({
        id: "dairy_yogurt_plain_lowfat",
        target: "Yogurt, plain, lowfat",
        query: "yogurt plain lowfat milk",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["plain yogurt lowfat", "lowfat yogurt plain", "regular yogurt lowfat"],
      }),
      t({
        id: "dairy_yogurt_plain_nonfat",
        target: "Yogurt, plain, nonfat",
        query: "yogurt plain nonfat milk",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["plain yogurt nonfat", "nonfat yogurt plain", "regular yogurt fat free"],
      }),
      t({
        id: "dairy_cottage_cheese_2",
        target: "Cottage cheese, 2% milkfat, lowfat",
        query: "cheese cottage lowfat 2% milkfat",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["cottage cheese 2%", "lowfat cottage cheese", "cottage cheese lowfat"],
      }),
      t({
        id: "dairy_cottage_cheese_1",
        target: "Cottage cheese, 1% milkfat, lowfat",
        query: "cheese cottage lowfat 1% milkfat",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["cottage cheese 1%", "cottage cheese very low fat", "lowfat cottage cheese 1%"],
      }),
      t({
        id: "dairy_cottage_cheese_nonfat",
        target: "Cottage cheese, nonfat",
        query: "cheese cottage nonfat uncreamed dry large or small curd",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["cottage cheese nonfat", "fat free cottage cheese", "nonfat cottage"],
      }),
      t({
        id: "dairy_cheddar",
        target: "Cheddar cheese",
        query: "cheese cheddar",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["cheddar", "cheddar cheese", "cheese cheddar"],
      }),
      t({
        id: "dairy_mozzarella_part_skim",
        target: "Mozzarella cheese, part skim milk",
        query: "cheese mozzarella part skim milk",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["mozzarella part skim", "part skim mozzarella", "cheese mozzarella part skim"],
      }),
      t({
        id: "dairy_mozzarella_whole",
        target: "Mozzarella cheese, whole milk",
        query: "cheese mozzarella whole milk",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["mozzarella whole milk", "whole milk mozzarella", "cheese mozzarella whole"],
      }),
      t({
        id: "dairy_parmesan",
        target: "Parmesan cheese, grated",
        query: "cheese parmesan grated",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["parmesan", "grated parmesan", "parmesan cheese"],
      }),
      t({
        id: "dairy_cream_cheese",
        target: "Cream cheese",
        query: "cheese cream",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["cream cheese", "cheese cream", "soft cream cheese"],
      }),
      t({
        id: "dairy_sour_cream_regular",
        target: "Sour cream, regular",
        query: "sour cream cultured",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["sour cream", "regular sour cream", "cultured sour cream"],
      }),
      t({
        id: "dairy_sour_cream_light",
        target: "Sour cream, light",
        query: "sour cream light cultured",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["light sour cream", "reduced fat sour cream", "sour cream lowfat"],
      }),
      t({
        id: "dairy_kefir_lowfat",
        target: "Kefir, lowfat",
        query: "milk kefir lowfat",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["kefir lowfat", "lowfat kefir", "kefir milk lowfat"],
      }),
      t({
        id: "dairy_buttermilk",
        target: "Buttermilk, fluid, cultured",
        query: "milk buttermilk fluid cultured lowfat",
        category: "dairy",
        preparationExpectation: "neutral",
        suggestedAliases: ["buttermilk", "cultured buttermilk", "fluid buttermilk"],
      }),
    ],
  },
  {
    batchId: "batch-06-produce-fats",
    label: "Fruits, vegetables, fats, extras",
    targets: [
      t({
        id: "fruit_apple_raw_skin",
        target: "Apple, raw, with skin",
        query: "apples raw with skin",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["apple raw", "raw apple with skin", "apples with skin"],
      }),
      t({
        id: "fruit_orange_raw",
        target: "Orange, raw",
        query: "oranges raw all commercial varieties",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["orange raw", "raw orange", "oranges raw"],
      }),
      t({
        id: "fruit_grapes_raw",
        target: "Grapes, raw",
        query: "grapes red or green european type raw",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["grapes raw", "raw grapes", "table grapes raw"],
      }),
      t({
        id: "fruit_strawberries_raw",
        target: "Strawberries, raw",
        query: "strawberries raw",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["strawberries raw", "raw strawberries", "strawberry raw"],
      }),
      t({
        id: "fruit_blueberries_raw",
        target: "Blueberries, raw",
        query: "blueberries raw",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["blueberries raw", "raw blueberries", "blueberry raw"],
      }),
      t({
        id: "fruit_raspberries_raw",
        target: "Raspberries, raw",
        query: "raspberries raw",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["raspberries raw", "raw raspberries", "raspberry raw"],
      }),
      t({
        id: "fruit_pineapple_raw",
        target: "Pineapple, raw",
        query: "pineapple raw all varieties",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["pineapple raw", "raw pineapple", "pineapple fresh"],
      }),
      t({
        id: "fruit_mango_raw",
        target: "Mango, raw",
        query: "mango raw",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["mango raw", "raw mango", "mango fresh raw"],
      }),
      t({
        id: "fruit_watermelon_raw",
        target: "Watermelon, raw",
        query: "watermelon raw",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["watermelon raw", "raw watermelon", "watermelon fresh"],
      }),
      t({
        id: "fruit_avocado_raw",
        target: "Avocado, raw",
        query: "avocados raw all commercial varieties",
        category: "fruit",
        preparationExpectation: "raw",
        suggestedAliases: ["avocado raw", "raw avocado", "avocados raw"],
      }),
      t({
        id: "veg_broccoli_raw",
        target: "Broccoli, raw",
        query: "broccoli raw",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["broccoli raw", "raw broccoli", "broccoli uncooked"],
      }),
      t({
        id: "veg_spinach_raw",
        target: "Spinach, raw",
        query: "spinach raw",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["spinach raw", "raw spinach", "spinach uncooked"],
      }),
      t({
        id: "veg_spinach_cooked",
        target: "Spinach, cooked, boiled, drained, without salt",
        query: "spinach cooked boiled drained without salt",
        category: "vegetables",
        preparationExpectation: "cooked",
        suggestedAliases: ["spinach cooked", "cooked spinach", "spinach boiled no salt"],
      }),
      t({
        id: "veg_lettuce_romaine_raw",
        target: "Lettuce, romaine, raw",
        query: "lettuce cos or romaine raw",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["romaine lettuce raw", "lettuce romaine raw", "romaine raw"],
      }),
      t({
        id: "veg_lettuce_iceberg_raw",
        target: "Lettuce, iceberg, raw",
        query: "lettuce iceberg includes crisphead types raw",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["iceberg lettuce raw", "lettuce iceberg raw", "iceberg raw"],
      }),
      t({
        id: "veg_tomato_raw",
        target: "Tomato, red, ripe, raw",
        query: "tomatoes red ripe raw year round average",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["tomato raw", "raw tomato", "red tomato raw"],
      }),
      t({
        id: "veg_onion_raw",
        target: "Onion, raw",
        query: "onions raw",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["onion raw", "raw onion", "onions raw"],
      }),
      t({
        id: "veg_pepper_green_raw",
        target: "Pepper, sweet, green, raw",
        query: "peppers sweet green raw",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["green bell pepper raw", "pepper green raw", "raw green pepper"],
      }),
      t({
        id: "veg_pepper_red_raw",
        target: "Pepper, sweet, red, raw",
        query: "peppers sweet red raw",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["red bell pepper raw", "pepper red raw", "raw red pepper"],
      }),
      t({
        id: "veg_carrot_raw",
        target: "Carrot, raw",
        query: "carrots raw",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["carrot raw", "raw carrot", "carrots raw"],
      }),
      t({
        id: "veg_carrot_cooked",
        target: "Carrot, cooked, boiled, drained, without salt",
        query: "carrots cooked boiled drained without salt",
        category: "vegetables",
        preparationExpectation: "cooked",
        suggestedAliases: ["carrot cooked", "cooked carrots", "carrots boiled no salt"],
      }),
      t({
        id: "veg_green_beans_raw",
        target: "Green beans, raw",
        query: "beans snap green raw",
        category: "vegetables",
        preparationExpectation: "raw",
        suggestedAliases: ["green beans raw", "raw green beans", "snap beans raw"],
      }),
      t({
        id: "veg_green_beans_cooked",
        target: "Green beans, cooked, boiled, drained, without salt",
        query: "beans snap green cooked boiled drained without salt",
        category: "vegetables",
        preparationExpectation: "cooked",
        suggestedAliases: ["green beans cooked", "cooked green beans", "snap beans cooked"],
      }),
      t({
        id: "veg_mixed_vegetables_frozen_cooked",
        target: "Mixed vegetables, frozen, cooked",
        query: "vegetables mixed frozen cooked boiled drained without salt",
        category: "vegetables",
        preparationExpectation: "cooked",
        suggestedAliases: ["mixed vegetables cooked", "frozen mixed vegetables cooked", "mixed veg cooked"],
      }),
      t({
        id: "fat_canola_oil",
        target: "Canola oil",
        query: "oil canola",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["canola oil", "oil canola", "rapeseed oil canola"],
      }),
      t({
        id: "fat_soybean_oil",
        target: "Soybean oil",
        query: "oil soybean salad or cooking",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["soybean oil", "oil soybean", "soy oil"],
      }),
      t({
        id: "fat_coconut_oil",
        target: "Coconut oil",
        query: "oil coconut",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["coconut oil", "oil coconut", "coconut cooking oil"],
      }),
      t({
        id: "fat_butter_salted",
        target: "Butter, salted",
        query: "butter salted",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["butter salted", "salted butter", "table butter salted"],
      }),
      t({
        id: "fat_butter_unsalted",
        target: "Butter, unsalted",
        query: "butter without salt",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["butter unsalted", "unsalted butter", "butter no salt"],
      }),
      t({
        id: "fat_peanut_butter",
        target: "Peanut butter, smooth",
        query: "peanut butter smooth",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["peanut butter smooth", "smooth peanut butter", "peanut butter"],
      }),
      t({
        id: "fat_almonds",
        target: "Almonds",
        query: "nuts almonds",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["almonds", "raw almonds", "almond nuts"],
      }),
      t({
        id: "fat_walnuts",
        target: "Walnuts",
        query: "nuts walnuts english",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["walnuts", "walnut nuts", "english walnuts"],
      }),
      t({
        id: "fat_cashews",
        target: "Cashews",
        query: "nuts cashew nuts",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["cashews", "cashew nuts", "raw cashews"],
      }),
      t({
        id: "fat_peanuts_dry_roasted",
        target: "Peanuts, dry roasted, without salt",
        query: "nuts peanuts all types dry roasted without salt",
        category: "fats_and_extras",
        preparationExpectation: "cooked",
        suggestedAliases: ["peanuts dry roasted", "dry roasted peanuts", "peanuts roasted no salt"],
      }),
      t({
        id: "extra_honey",
        target: "Honey",
        query: "honey",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["honey", "bee honey", "honey plain"],
      }),
      t({
        id: "extra_sugar_granulated",
        target: "Sugar, granulated",
        query: "sugar granulated",
        category: "fats_and_extras",
        preparationExpectation: "neutral",
        suggestedAliases: ["granulated sugar", "white sugar", "table sugar"],
      }),
    ],
  },
];

export const CATALOG_DISCOVERY_TARGETS: CatalogDiscoveryTarget[] = CATALOG_TARGET_BATCHES.flatMap(
  (batch) => batch.targets,
);

export function getTargetsForBatch(batchId: string | null): CatalogDiscoveryTarget[] {
  if (!batchId) {
    return CATALOG_DISCOVERY_TARGETS;
  }
  const batch = CATALOG_TARGET_BATCHES.find((entry) => entry.batchId === batchId);
  if (!batch) {
    throw new Error(`Unknown batch id '${batchId}'.`);
  }
  return batch.targets;
}
