import type { FoodCatalogPilotManifest } from "../../src/lib/usda/catalog-pilot";

export const FOOD_CATALOG_PILOT_MANIFEST: FoodCatalogPilotManifest = {
  version: "food-catalog-pilot-manifest-v1",
  records: [
    {
      target: "Chicken breast, boneless, skinless, raw",
      fdcId: 171077,
      displayName: "Chicken breast, boneless, skinless, raw",
      exactUsdaDescription: "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["chicken breast raw", "raw chicken breast", "skinless chicken breast raw"],
      preparationExpectation: "raw",
      notes: "Selected for explicit boneless/skinless/raw wording with complete macro fields.",
    },
    {
      target: "Chicken breast, boneless, skinless, cooked or roasted",
      fdcId: 171140,
      displayName: "Chicken breast, boneless, skinless, cooked, braised",
      exactUsdaDescription:
        "Chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, braised",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["chicken breast cooked", "cooked chicken breast", "chicken breast braised"],
      preparationExpectation: "cooked",
      notes: "Retains boneless/skinless specificity while clearly representing cooked poultry.",
    },
    {
      target: "Chicken thigh, raw",
      fdcId: 173627,
      displayName: "Chicken thigh, meat only, raw",
      exactUsdaDescription: "Chicken, broilers or fryers, dark meat, thigh, meat only, raw",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["chicken thigh raw", "raw chicken thigh", "chicken thigh meat only raw"],
      preparationExpectation: "raw",
      notes: "Avoids skin-in variant to keep a cleaner lean-meat reference.",
    },
    {
      target: "Chicken thigh, cooked or roasted",
      fdcId: 172388,
      displayName: "Chicken thigh, meat only, cooked, roasted",
      exactUsdaDescription: "Chicken, broilers or fryers, thigh, meat only, cooked, roasted",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["chicken thigh cooked", "cooked chicken thigh", "chicken thigh roasted"],
      preparationExpectation: "cooked",
      notes: "Direct raw/cooked counterpart to the selected raw chicken thigh record.",
    },
    {
      target: "Ground beef, approximately 90% lean / 10% fat, raw",
      fdcId: 174030,
      displayName: "Ground beef, 90% lean / 10% fat, raw",
      exactUsdaDescription: "Beef, ground, 90% lean meat / 10% fat, raw",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["ground beef 90 10 raw", "90 lean ground beef raw", "beef mince 90 10 raw"],
      preparationExpectation: "raw",
      notes: "Chosen exact 90/10 raw record with complete core macros.",
    },
    {
      target: "Ground beef, approximately 90% lean / 10% fat, cooked",
      fdcId: 171793,
      displayName: "Ground beef, 90% lean / 10% fat, patty, cooked, pan-broiled",
      exactUsdaDescription: "Beef, ground, 90% lean meat / 10% fat, patty, cooked, pan-broiled",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["ground beef 90 10 cooked", "90 lean ground beef cooked", "ground beef patty cooked"],
      preparationExpectation: "cooked",
      notes: "Maintains 90/10 identity while using a specific cooked preparation state.",
    },
    {
      target: "Whole egg",
      fdcId: 171287,
      displayName: "Egg, whole, raw, fresh",
      exactUsdaDescription: "Egg, whole, raw, fresh",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["whole egg raw", "egg whole raw", "raw whole egg"],
      preparationExpectation: "neutral",
      notes: "Fresh whole egg baseline without frozen/salted modifiers.",
    },
    {
      target: "Egg white",
      fdcId: 172183,
      displayName: "Egg white, raw, fresh",
      exactUsdaDescription: "Egg, white, raw, fresh",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["egg white raw", "raw egg white", "egg whites raw"],
      preparationExpectation: "neutral",
      notes: "Fresh egg-white-only counterpart to whole egg entry.",
    },
    {
      target: "Salmon, cooked",
      fdcId: 171998,
      displayName: "Salmon, Atlantic, wild, cooked, dry heat",
      exactUsdaDescription: "Fish, salmon, Atlantic, wild, cooked, dry heat",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["salmon cooked", "atlantic salmon cooked", "wild salmon cooked"],
      preparationExpectation: "cooked",
      notes: "Selected clearly cooked wild Atlantic salmon record.",
    },
    {
      target: "Tilapia, cooked",
      fdcId: 175177,
      displayName: "Tilapia, cooked, dry heat",
      exactUsdaDescription: "Fish, tilapia, cooked, dry heat",
      expectedDataType: "SR Legacy",
      category: "protein",
      aliases: ["tilapia cooked", "cooked tilapia", "tilapia dry heat"],
      preparationExpectation: "cooked",
      notes: "Clean generic tilapia cooked entry with complete core macros.",
    },
    {
      target: "White rice, long-grain, cooked",
      fdcId: 168878,
      displayName: "Rice, white, long-grain, enriched, cooked",
      exactUsdaDescription: "Rice, white, long-grain, regular, enriched, cooked",
      expectedDataType: "SR Legacy",
      category: "carbohydrate",
      aliases: ["white rice cooked", "long grain white rice cooked", "cooked white rice"],
      preparationExpectation: "cooked",
      notes: "Exact long-grain cooked white rice reference.",
    },
    {
      target: "Brown rice, cooked",
      fdcId: 169704,
      displayName: "Rice, brown, long-grain, cooked",
      exactUsdaDescription: "Rice, brown, long-grain, cooked (Includes foods for USDA's Food Distribution Program)",
      expectedDataType: "SR Legacy",
      category: "carbohydrate",
      aliases: ["brown rice cooked", "long grain brown rice cooked", "cooked brown rice"],
      preparationExpectation: "cooked",
      notes: "Closest exact long-grain cooked brown-rice generic record found.",
    },
    {
      target: "Oats, dry",
      fdcId: 173904,
      displayName: "Oats, regular and quick, dry",
      exactUsdaDescription: "Cereals, oats, regular and quick, not fortified, dry",
      expectedDataType: "SR Legacy",
      category: "carbohydrate",
      aliases: ["oats dry", "dry oats", "rolled oats dry"],
      preparationExpectation: "neutral",
      notes: "Avoids flavored instant oat variants.",
    },
    {
      target: "Potato, baked or cooked",
      fdcId: 170030,
      displayName: "Potato, russet, flesh and skin, baked",
      exactUsdaDescription: "Potatoes, Russet, flesh and skin, baked",
      expectedDataType: "SR Legacy",
      category: "carbohydrate",
      aliases: ["potato baked", "baked russet potato", "potato flesh and skin baked"],
      preparationExpectation: "cooked",
      notes: "Specific baked potato form with skin and flesh retained.",
    },
    {
      target: "Sweet potato, baked or cooked",
      fdcId: 168483,
      displayName: "Sweet potato, baked in skin, flesh, without salt",
      exactUsdaDescription: "Sweet potato, cooked, baked in skin, flesh, without salt",
      expectedDataType: "SR Legacy",
      category: "carbohydrate",
      aliases: ["sweet potato baked", "baked sweet potato", "sweet potato cooked baked"],
      preparationExpectation: "cooked",
      notes: "Explicit baked sweet potato with no added salt variant.",
    },
    {
      target: "Banana, raw",
      fdcId: 173944,
      displayName: "Bananas, raw",
      exactUsdaDescription: "Bananas, raw",
      expectedDataType: "SR Legacy",
      category: "produce_and_staples",
      aliases: ["banana raw", "raw banana", "bananas raw"],
      preparationExpectation: "raw",
      notes: "Selected to avoid banana-pepper false matches.",
    },
    {
      target: "Broccoli, cooked",
      fdcId: 169967,
      displayName: "Broccoli, cooked, boiled, drained, without salt",
      exactUsdaDescription: "Broccoli, cooked, boiled, drained, without salt",
      expectedDataType: "SR Legacy",
      category: "produce_and_staples",
      aliases: ["broccoli cooked", "cooked broccoli", "broccoli boiled without salt"],
      preparationExpectation: "cooked",
      notes: "Uses the no-salt cooked broccoli variant for cleaner baseline values.",
    },
    {
      target: "Whole milk",
      fdcId: 171265,
      displayName: "Milk, whole, 3.25% milkfat, with added vitamin D",
      exactUsdaDescription: "Milk, whole, 3.25% milkfat, with added vitamin D",
      expectedDataType: "SR Legacy",
      category: "produce_and_staples",
      aliases: ["whole milk", "milk 3.25%", "whole milk vitamin d"],
      preparationExpectation: "neutral",
      notes: "Specific standard whole-milk profile with complete macros.",
    },
    {
      target: "Plain Greek yogurt",
      fdcId: 170894,
      displayName: "Yogurt, Greek, plain, nonfat",
      exactUsdaDescription:
        "Yogurt, Greek, plain, nonfat (Includes foods for USDA's Food Distribution Program)",
      expectedDataType: "SR Legacy",
      category: "produce_and_staples",
      aliases: ["greek yogurt plain", "plain greek yogurt nonfat", "nonfat greek yogurt plain"],
      preparationExpectation: "neutral",
      notes:
        "Foundation candidate 330137 did not resolve via detail endpoint during verification; selected closest exact generic SR record.",
    },
    {
      target: "Olive oil",
      fdcId: 171413,
      displayName: "Olive oil, salad or cooking",
      exactUsdaDescription: "Oil, olive, salad or cooking",
      expectedDataType: "SR Legacy",
      category: "produce_and_staples",
      aliases: ["olive oil", "oil olive", "olive oil cooking"],
      preparationExpectation: "neutral",
      notes: "Generic olive-oil entry, avoiding mixed-oil blends and mayo variants.",
    },
  ],
};
