import type { FoodCatalogManifestRecord, FoodCatalogPilotManifest } from "../../src/lib/usda/catalog-pilot";
import { CATALOG_DISCOVERY_TARGETS } from "./catalog-target-batches";

interface ExpansionSelectionRecord {
  targetId: string;
  fdcId: number;
  expectedDataType: string;
  exactUsdaDescription: string;
}

const PILOT_LOCKED_RECORDS: FoodCatalogManifestRecord[] = [
  {
    target: "Chicken breast, boneless, skinless, raw",
    fdcId: 171077,
    displayName: "Chicken breast, boneless, skinless, raw",
    exactUsdaDescription: "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw",
    expectedDataType: "SR Legacy",
    category: "protein",
    aliases: ["chicken breast raw", "raw chicken breast", "skinless chicken breast raw"],
    preparationExpectation: "raw",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Chicken breast, boneless, skinless, cooked or roasted",
    fdcId: 171140,
    displayName: "Chicken breast, boneless, skinless, cooked, braised",
    exactUsdaDescription: "Chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, braised",
    expectedDataType: "SR Legacy",
    category: "protein",
    aliases: ["chicken breast cooked", "cooked chicken breast", "chicken breast braised"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Chicken thigh, raw",
    fdcId: 173627,
    displayName: "Chicken thigh, meat only, raw",
    exactUsdaDescription: "Chicken, broilers or fryers, dark meat, thigh, meat only, raw",
    expectedDataType: "SR Legacy",
    category: "protein",
    aliases: ["chicken thigh raw", "raw chicken thigh", "chicken thigh meat only raw"],
    preparationExpectation: "raw",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Chicken thigh, cooked or roasted",
    fdcId: 172388,
    displayName: "Chicken thigh, meat only, cooked, roasted",
    exactUsdaDescription: "Chicken, broilers or fryers, thigh, meat only, cooked, roasted",
    expectedDataType: "SR Legacy",
    category: "protein",
    aliases: ["chicken thigh cooked", "cooked chicken thigh", "chicken thigh roasted"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Ground beef, approximately 90% lean / 10% fat, raw",
    fdcId: 174030,
    displayName: "Ground beef, 90% lean / 10% fat, raw",
    exactUsdaDescription: "Beef, ground, 90% lean meat / 10% fat, raw",
    expectedDataType: "SR Legacy",
    category: "protein",
    aliases: ["ground beef 90 10 raw", "90 lean ground beef raw", "beef mince 90 10 raw"],
    preparationExpectation: "raw",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Ground beef, approximately 90% lean / 10% fat, cooked",
    fdcId: 171793,
    displayName: "Ground beef, 90% lean / 10% fat, patty, cooked, pan-broiled",
    exactUsdaDescription: "Beef, ground, 90% lean meat / 10% fat, patty, cooked, pan-broiled",
    expectedDataType: "SR Legacy",
    category: "protein",
    aliases: ["ground beef 90 10 cooked", "90 lean ground beef cooked", "ground beef patty cooked"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Whole egg",
    fdcId: 171287,
    displayName: "Egg, whole, raw, fresh",
    exactUsdaDescription: "Egg, whole, raw, fresh",
    expectedDataType: "SR Legacy",
    category: "protein",
    aliases: ["whole egg raw", "egg whole raw", "raw whole egg"],
    preparationExpectation: "neutral",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Egg white",
    fdcId: 172183,
    displayName: "Egg white, raw, fresh",
    exactUsdaDescription: "Egg, white, raw, fresh",
    expectedDataType: "SR Legacy",
    category: "protein",
    aliases: ["egg white raw", "raw egg white", "egg whites raw"],
    preparationExpectation: "neutral",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Salmon, cooked",
    fdcId: 171998,
    displayName: "Salmon, Atlantic, wild, cooked, dry heat",
    exactUsdaDescription: "Fish, salmon, Atlantic, wild, cooked, dry heat",
    expectedDataType: "SR Legacy",
    category: "seafood",
    aliases: ["salmon cooked", "atlantic salmon cooked", "wild salmon cooked"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Tilapia, cooked",
    fdcId: 175177,
    displayName: "Tilapia, cooked, dry heat",
    exactUsdaDescription: "Fish, tilapia, cooked, dry heat",
    expectedDataType: "SR Legacy",
    category: "seafood",
    aliases: ["tilapia cooked", "cooked tilapia", "tilapia dry heat"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "White rice, long-grain, cooked",
    fdcId: 168878,
    displayName: "Rice, white, long-grain, enriched, cooked",
    exactUsdaDescription: "Rice, white, long-grain, regular, enriched, cooked",
    expectedDataType: "SR Legacy",
    category: "grains_and_starches",
    aliases: ["white rice cooked", "long grain white rice cooked", "cooked white rice"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Brown rice, cooked",
    fdcId: 169704,
    displayName: "Rice, brown, long-grain, cooked",
    exactUsdaDescription: "Rice, brown, long-grain, cooked (Includes foods for USDA's Food Distribution Program)",
    expectedDataType: "SR Legacy",
    category: "grains_and_starches",
    aliases: ["brown rice cooked", "long grain brown rice cooked", "cooked brown rice"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Oats, dry",
    fdcId: 173904,
    displayName: "Oats, regular and quick, dry",
    exactUsdaDescription: "Cereals, oats, regular and quick, not fortified, dry",
    expectedDataType: "SR Legacy",
    category: "grains_and_starches",
    aliases: ["oats dry", "dry oats", "rolled oats dry"],
    preparationExpectation: "neutral",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Potato, baked or cooked",
    fdcId: 170030,
    displayName: "Potato, russet, flesh and skin, baked",
    exactUsdaDescription: "Potatoes, Russet, flesh and skin, baked",
    expectedDataType: "SR Legacy",
    category: "grains_and_starches",
    aliases: ["potato baked", "baked russet potato", "potato flesh and skin baked"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Sweet potato, baked or cooked",
    fdcId: 168483,
    displayName: "Sweet potato, baked in skin, flesh, without salt",
    exactUsdaDescription: "Sweet potato, cooked, baked in skin, flesh, without salt",
    expectedDataType: "SR Legacy",
    category: "grains_and_starches",
    aliases: ["sweet potato baked", "baked sweet potato", "sweet potato cooked baked"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Banana, raw",
    fdcId: 173944,
    displayName: "Bananas, raw",
    exactUsdaDescription: "Bananas, raw",
    expectedDataType: "SR Legacy",
    category: "fruit",
    aliases: ["banana raw", "raw banana", "bananas raw"],
    preparationExpectation: "raw",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Broccoli, cooked",
    fdcId: 169967,
    displayName: "Broccoli, cooked, boiled, drained, without salt",
    exactUsdaDescription: "Broccoli, cooked, boiled, drained, without salt",
    expectedDataType: "SR Legacy",
    category: "vegetables",
    aliases: ["broccoli cooked", "cooked broccoli", "broccoli boiled without salt"],
    preparationExpectation: "cooked",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Whole milk",
    fdcId: 171265,
    displayName: "Milk, whole, 3.25% milkfat, with added vitamin D",
    exactUsdaDescription: "Milk, whole, 3.25% milkfat, with added vitamin D",
    expectedDataType: "SR Legacy",
    category: "dairy",
    aliases: ["whole milk", "milk 3.25%", "whole milk vitamin d"],
    preparationExpectation: "neutral",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Plain Greek yogurt",
    fdcId: 170894,
    displayName: "Yogurt, Greek, plain, nonfat",
    exactUsdaDescription: "Yogurt, Greek, plain, nonfat (Includes foods for USDA's Food Distribution Program)",
    expectedDataType: "SR Legacy",
    category: "dairy",
    aliases: ["greek yogurt plain", "plain greek yogurt nonfat", "nonfat greek yogurt plain"],
    preparationExpectation: "neutral",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
  {
    target: "Olive oil",
    fdcId: 171413,
    displayName: "Olive oil, salad or cooking",
    exactUsdaDescription: "Oil, olive, salad or cooking",
    expectedDataType: "SR Legacy",
    category: "fats_and_extras",
    aliases: ["olive oil", "oil olive", "olive oil cooking"],
    preparationExpectation: "neutral",
    notes: "Phase 2A locked pilot record; unchanged in Phase 2C.",
  },
];

const EXPANSION_SELECTIONS: ExpansionSelectionRecord[] = [
  { targetId: "grain_tortilla_flour", fdcId: 167535, expectedDataType: "SR Legacy", exactUsdaDescription: "Tortillas, ready-to-bake or -fry, flour, shelf stable" },
  { targetId: "fruit_raspberries_raw", fdcId: 167755, expectedDataType: "SR Legacy", exactUsdaDescription: "Raspberries, raw" },
  { targetId: "fruit_strawberries_raw", fdcId: 167762, expectedDataType: "SR Legacy", exactUsdaDescription: "Strawberries, raw" },
  { targetId: "fruit_watermelon_raw", fdcId: 167765, expectedDataType: "SR Legacy", exactUsdaDescription: "Watermelon, raw" },
  { targetId: "protein_pork_chop_raw", fdcId: 167822, expectedDataType: "SR Legacy", exactUsdaDescription: "Pork, fresh, loin, blade (chops or roasts), bone-in, separable lean and fat, raw" },
  { targetId: "protein_pork_chop_cooked", fdcId: 167824, expectedDataType: "SR Legacy", exactUsdaDescription: "Pork, fresh, loin, blade (chops), bone-in, separable lean and fat, cooked, broiled" },
  { targetId: "protein_pork_tenderloin_raw", fdcId: 168249, expectedDataType: "SR Legacy", exactUsdaDescription: "Pork, fresh, loin, tenderloin, separable lean only, raw" },
  { targetId: "protein_pork_tenderloin_cooked", fdcId: 168250, expectedDataType: "SR Legacy", exactUsdaDescription: "Pork, fresh, loin, tenderloin, separable lean only, cooked, roasted" },
  { targetId: "protein_pork_loin_raw", fdcId: 168251, expectedDataType: "SR Legacy", exactUsdaDescription: "Pork, fresh, loin, top loin (chops), boneless, separable lean only, raw" },
  { targetId: "protein_pork_loin_cooked", fdcId: 168253, expectedDataType: "SR Legacy", exactUsdaDescription: "Pork, fresh, loin, top loin (chops), boneless, separable lean only, cooked, broiled" },
  { targetId: "grain_corn_sweet_yellow_cooked", fdcId: 168401, expectedDataType: "SR Legacy", exactUsdaDescription: "Corn, sweet, yellow, frozen, kernels on cob, cooked, boiled, drained, without salt" },
  { targetId: "veg_spinach_raw", fdcId: 168462, expectedDataType: "SR Legacy", exactUsdaDescription: "Spinach, raw" },
  { targetId: "veg_spinach_cooked", fdcId: 168463, expectedDataType: "SR Legacy", exactUsdaDescription: "Spinach, cooked, boiled, drained, without salt" },
  { targetId: "grain_sweet_potato_boiled", fdcId: 168484, expectedDataType: "SR Legacy", exactUsdaDescription: "Sweet potato, cooked, boiled, without skin" },
  { targetId: "grain_potato_mashed_milk_butter", fdcId: 168555, expectedDataType: "SR Legacy", exactUsdaDescription: "Potatoes, mashed, home-prepared, whole milk and butter added" },
  { targetId: "protein_beef_flank_raw", fdcId: 168609, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, flank, steak, separable lean only, trimmed to 0\" fat, choice, raw" },
  { targetId: "protein_beef_flank_cooked", fdcId: 168611, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, flank, steak, separable lean only, trimmed to 0\" fat, choice, cooked, broiled" },
  { targetId: "protein_beef_chuck_cooked", fdcId: 168674, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, chuck eye roast, boneless, America's Beef Roast, separable lean only, trimmed to 0\" fat, all grades, cooked, roasted" },
  { targetId: "protein_beef_chuck_raw", fdcId: 168742, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, chuck eye roast, boneless, America's Beef Roast, separable lean only, trimmed to 0\" fat, select, raw" },
  { targetId: "grain_white_rice_medium_cooked", fdcId: 168880, expectedDataType: "SR Legacy", exactUsdaDescription: "Rice, white, medium-grain, enriched, cooked" },
  { targetId: "grain_white_rice_short_cooked", fdcId: 168882, expectedDataType: "SR Legacy", exactUsdaDescription: "Rice, white, short-grain, enriched, cooked" },
  { targetId: "grain_wild_rice_cooked", fdcId: 168897, expectedDataType: "SR Legacy", exactUsdaDescription: "Wild rice, cooked" },
  { targetId: "grain_pasta_whole_wheat_cooked", fdcId: 168910, expectedDataType: "SR Legacy", exactUsdaDescription: "Pasta, whole-wheat, cooked (Includes foods for USDA's Food Distribution Program)" },
  { targetId: "grain_quinoa_cooked", fdcId: 168917, expectedDataType: "SR Legacy", exactUsdaDescription: "Quinoa, cooked" },
  { targetId: "fruit_orange_raw", fdcId: 169097, expectedDataType: "SR Legacy", exactUsdaDescription: "Oranges, raw, all commercial varieties" },
  { targetId: "fruit_pineapple_raw", fdcId: 169124, expectedDataType: "SR Legacy", exactUsdaDescription: "Pineapple, raw, all varieties" },
  { targetId: "veg_green_beans_cooked", fdcId: 169141, expectedDataType: "SR Legacy", exactUsdaDescription: "Beans, snap, green, cooked, boiled, drained, without salt" },
  { targetId: "veg_lettuce_romaine_raw", fdcId: 169247, expectedDataType: "SR Legacy", exactUsdaDescription: "Lettuce, cos or romaine, raw" },
  { targetId: "veg_lettuce_iceberg_raw", fdcId: 169248, expectedDataType: "SR Legacy", exactUsdaDescription: "Lettuce, iceberg (includes crisphead types), raw" },
  { targetId: "extra_honey", fdcId: 169640, expectedDataType: "SR Legacy", exactUsdaDescription: "Honey" },
  { targetId: "extra_sugar_granulated", fdcId: 169655, expectedDataType: "SR Legacy", exactUsdaDescription: "Sugars, granulated" },
  { targetId: "grain_white_rice_parboiled_cooked", fdcId: 169708, expectedDataType: "SR Legacy", exactUsdaDescription: "Rice, white, long-grain, parboiled, enriched, cooked" },
  { targetId: "grain_pasta_spaghetti_cooked", fdcId: 169737, expectedDataType: "SR Legacy", exactUsdaDescription: "Pasta, cooked, enriched, without added salt" },
  { targetId: "grain_pasta_macaroni_cooked", fdcId: 169751, expectedDataType: "SR Legacy", exactUsdaDescription: "Pasta, cooked, enriched, with added salt" },
  { targetId: "fruit_mango_raw", fdcId: 169910, expectedDataType: "SR Legacy", exactUsdaDescription: "Mangos, raw" },
  { targetId: "veg_green_beans_raw", fdcId: 169961, expectedDataType: "SR Legacy", exactUsdaDescription: "Beans, snap, green, raw" },
  { targetId: "veg_carrot_cooked", fdcId: 169984, expectedDataType: "SR Legacy", exactUsdaDescription: "Carrots, frozen, cooked, boiled, drained, without salt" },
  { targetId: "veg_onion_raw", fdcId: 170000, expectedDataType: "SR Legacy", exactUsdaDescription: "Onions, raw" },
  { targetId: "grain_green_peas_cooked", fdcId: 170017, expectedDataType: "SR Legacy", exactUsdaDescription: "Peas, green, frozen, cooked, boiled, drained, without salt" },
  { targetId: "grain_potato_boiled_no_salt", fdcId: 170049, expectedDataType: "SR Legacy", exactUsdaDescription: "Potatoes, frozen, whole, cooked, boiled, drained, without salt" },
  { targetId: "veg_pepper_red_raw", fdcId: 170108, expectedDataType: "SR Legacy", exactUsdaDescription: "Peppers, sweet, red, raw" },
  { targetId: "fat_cashews", fdcId: 170162, expectedDataType: "SR Legacy", exactUsdaDescription: "Nuts, cashew nuts, raw" },
  { targetId: "fat_walnuts", fdcId: 170187, expectedDataType: "SR Legacy", exactUsdaDescription: "Nuts, walnuts, english" },
  { targetId: "protein_beef_round_cooked", fdcId: 170227, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, round, bottom round roast, separable lean only, trimmed to 0\" fat, select, cooked, roasted" },
  { targetId: "veg_broccoli_raw", fdcId: 170379, expectedDataType: "SR Legacy", exactUsdaDescription: "Broccoli, raw" },
  { targetId: "veg_carrot_raw", fdcId: 170393, expectedDataType: "SR Legacy", exactUsdaDescription: "Carrots, raw" },
  { targetId: "veg_pepper_green_raw", fdcId: 170427, expectedDataType: "SR Legacy", exactUsdaDescription: "Peppers, sweet, green, raw" },
  { targetId: "veg_tomato_raw", fdcId: 170457, expectedDataType: "SR Legacy", exactUsdaDescription: "Tomatoes, red, ripe, raw, year round average" },
  { targetId: "veg_mixed_vegetables_frozen_cooked", fdcId: 170472, expectedDataType: "SR Legacy", exactUsdaDescription: "Vegetables, mixed, frozen, cooked, boiled, drained, without salt" },
  { targetId: "fat_almonds", fdcId: 170567, expectedDataType: "SR Legacy", exactUsdaDescription: "Nuts, almonds" },
  { targetId: "protein_beef_tenderloin_cooked", fdcId: 170642, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, loin, tenderloin steak, boneless, separable lean only, trimmed to 0\" fat, choice, cooked, grilled" },
  { targetId: "dairy_mozzarella_whole", fdcId: 170845, expectedDataType: "SR Legacy", exactUsdaDescription: "Cheese, mozzarella, whole milk" },
  { targetId: "dairy_mozzarella_part_skim", fdcId: 170847, expectedDataType: "SR Legacy", exactUsdaDescription: "Cheese, mozzarella, part skim milk" },
  { targetId: "dairy_buttermilk", fdcId: 170874, expectedDataType: "SR Legacy", exactUsdaDescription: "Milk, buttermilk, fluid, cultured, lowfat" },
  { targetId: "dairy_yogurt_plain_nonfat", fdcId: 170887, expectedDataType: "SR Legacy", exactUsdaDescription: "Yogurt, plain, skim milk" },
  { targetId: "dairy_greek_yogurt_lowfat", fdcId: 170903, expectedDataType: "SR Legacy", exactUsdaDescription: "Yogurt, Greek, plain, lowfat" },
  { targetId: "protein_turkey_breast_raw", fdcId: 171098, expectedDataType: "SR Legacy", exactUsdaDescription: "Turkey, whole, breast, meat only, raw" },
  { targetId: "protein_ground_chicken_raw", fdcId: 171116, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, ground, raw" },
  { targetId: "protein_ground_chicken_cooked", fdcId: 171117, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, ground, crumbles, cooked, pan-browned" },
  { targetId: "dairy_parmesan", fdcId: 171247, expectedDataType: "SR Legacy", exactUsdaDescription: "Cheese, parmesan, grated" },
  { targetId: "dairy_milk_2_percent", fdcId: 171267, expectedDataType: "SR Legacy", exactUsdaDescription: "Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D" },
  { targetId: "dairy_milk_nonfat", fdcId: 171269, expectedDataType: "SR Legacy", exactUsdaDescription: "Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)" },
  { targetId: "dairy_yogurt_plain_whole", fdcId: 171284, expectedDataType: "SR Legacy", exactUsdaDescription: "Yogurt, plain, whole milk" },
  { targetId: "dairy_greek_yogurt_whole", fdcId: 171304, expectedDataType: "SR Legacy", exactUsdaDescription: "Yogurt, Greek, plain, whole milk" },
  { targetId: "fat_soybean_oil", fdcId: 171411, expectedDataType: "SR Legacy", exactUsdaDescription: "Oil, soybean, salad or cooking" },
  { targetId: "fat_coconut_oil", fdcId: 171412, expectedDataType: "SR Legacy", exactUsdaDescription: "Oil, coconut" },
  { targetId: "protein_chicken_breast_cooked_roasted", fdcId: 171477, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, broilers or fryers, breast, meat only, cooked, roasted" },
  { targetId: "protein_turkey_breast_cooked", fdcId: 171496, expectedDataType: "SR Legacy", exactUsdaDescription: "Turkey, whole, breast, meat only, cooked, roasted" },
  { targetId: "protein_turkey_thigh_raw", fdcId: 171531, expectedDataType: "SR Legacy", exactUsdaDescription: "Turkey, thigh, from whole bird, meat only, raw" },
  { targetId: "protein_chicken_breast_cooked_grilled", fdcId: 171534, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, grilled" },
  { targetId: "grain_oats_instant_dry", fdcId: 171661, expectedDataType: "SR Legacy", exactUsdaDescription: "Cereals, oats, instant, fortified, plain, dry" },
  { targetId: "grain_oatmeal_cooked_water", fdcId: 171675, expectedDataType: "SR Legacy", exactUsdaDescription: "Cereals, oats, regular and quick and instant, unenriched, cooked with water (includes boiling and microwaving), with salt" },
  { targetId: "fruit_apple_raw_skin", fdcId: 171688, expectedDataType: "SR Legacy", exactUsdaDescription: "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)" },
  { targetId: "fruit_avocado_raw", fdcId: 171705, expectedDataType: "SR Legacy", exactUsdaDescription: "Avocados, raw, all commercial varieties" },
  { targetId: "fruit_blueberries_raw", fdcId: 171711, expectedDataType: "SR Legacy", exactUsdaDescription: "Blueberries, raw" },
  { targetId: "protein_beef_round_raw", fdcId: 171744, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, round, top round roast, boneless, separable lean and fat, trimmed to 0\" fat, select, raw" },
  { targetId: "protein_ground_beef_95_raw", fdcId: 171790, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, ground, 95% lean meat / 5% fat, raw" },
  { targetId: "protein_ground_beef_95_cooked", fdcId: 171791, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, ground, 95% lean meat / 5% fat, patty, cooked, broiled" },
  { targetId: "protein_ground_beef_85_raw", fdcId: 171796, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, ground, 85% lean meat / 15% fat, raw (Includes foods for USDA's Food Distribution Program)" },
  { targetId: "protein_ground_beef_80_cooked", fdcId: 171797, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, ground, 80% lean meat / 20% fat, patty, cooked, broiled" },
  { targetId: "protein_beef_tenderloin_raw", fdcId: 171803, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, tenderloin, steak, separable lean only, trimmed to 1/8\" fat, select, raw" },
  { targetId: "protein_beef_sirloin_raw", fdcId: 171804, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, top sirloin, steak, separable lean only, trimmed to 1/8\" fat, select, raw" },
  { targetId: "seafood_cod_raw", fdcId: 171955, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, cod, Atlantic, raw" },
  { targetId: "seafood_cod_cooked", fdcId: 171956, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, cod, Atlantic, cooked, dry heat" },
  { targetId: "seafood_shrimp_cooked", fdcId: 171971, expectedDataType: "SR Legacy", exactUsdaDescription: "Crustaceans, shrimp, mixed species, cooked, moist heat (may contain additives to retain moisture)" },
  { targetId: "seafood_tuna_light_canned_water", fdcId: 171986, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, tuna, light, canned in water, without salt, drained solids" },
  { targetId: "seafood_tuna_white_canned_water", fdcId: 171988, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, tuna, white, canned in water, without salt, drained solids" },
  { targetId: "seafood_tuna_yellowfin_cooked", fdcId: 172006, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, tuna, yellowfin, fresh, cooked, dry heat" },
  { targetId: "dairy_cottage_cheese_nonfat", fdcId: 172181, expectedDataType: "SR Legacy", exactUsdaDescription: "Cheese, cottage, nonfat, uncreamed, dry, large or small curd" },
  { targetId: "dairy_cottage_cheese_2", fdcId: 172182, expectedDataType: "SR Legacy", exactUsdaDescription: "Cheese, cottage, lowfat, 2% milkfat" },
  { targetId: "protein_egg_omelet_plain", fdcId: 172185, expectedDataType: "SR Legacy", exactUsdaDescription: "Egg, whole, cooked, omelet" },
  { targetId: "protein_egg_whole_scrambled", fdcId: 172187, expectedDataType: "SR Legacy", exactUsdaDescription: "Egg, whole, cooked, scrambled" },
  { targetId: "fat_canola_oil", fdcId: 172336, expectedDataType: "SR Legacy", exactUsdaDescription: "Oil, canola" },
  { targetId: "protein_chicken_drumstick_raw", fdcId: 172373, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, broilers or fryers, drumstick, meat and skin, raw" },
  { targetId: "protein_chicken_thigh_raw_skin_on", fdcId: 172385, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, broilers or fryers, thigh, meat and skin, raw" },
  { targetId: "protein_chicken_wing_raw", fdcId: 172390, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, broilers or fryers, wing, meat and skin, raw" },
  { targetId: "grain_lentils_cooked", fdcId: 172421, expectedDataType: "SR Legacy", exactUsdaDescription: "Lentils, mature seeds, cooked, boiled, without salt" },
  { targetId: "grain_bread_whole_wheat", fdcId: 172688, expectedDataType: "SR Legacy", exactUsdaDescription: "Bread, whole-wheat, commercially prepared" },
  { targetId: "grain_bread_white", fdcId: 172818, expectedDataType: "SR Legacy", exactUsdaDescription: "Bread, white, commercially prepared, low sodium, no salt" },
  { targetId: "protein_ground_turkey_93_raw", fdcId: 172850, expectedDataType: "SR Legacy", exactUsdaDescription: "Turkey, ground, 93% lean, 7% fat, raw" },
  { targetId: "protein_ground_turkey_93_cooked", fdcId: 172851, expectedDataType: "SR Legacy", exactUsdaDescription: "Turkey, ground, 93% lean, 7% fat, pan-broiled crumbles" },
  { targetId: "protein_turkey_thigh_cooked", fdcId: 172877, expectedDataType: "SR Legacy", exactUsdaDescription: "Turkey, retail parts, thigh, meat only, cooked, roasted" },
  { targetId: "protein_ground_beef_93_raw", fdcId: 173110, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, ground, 93% lean meat / 7% fat, raw" },
  { targetId: "grain_tortilla_corn", fdcId: 173241, expectedDataType: "SR Legacy", exactUsdaDescription: "Tortillas, ready-to-bake or -fry, corn, without added salt" },
  { targetId: "fat_butter_salted", fdcId: 173410, expectedDataType: "SR Legacy", exactUsdaDescription: "Butter, salted" },
  { targetId: "dairy_cottage_cheese_1", fdcId: 173417, expectedDataType: "SR Legacy", exactUsdaDescription: "Cheese, cottage, lowfat, 1% milkfat" },
  { targetId: "dairy_cream_cheese", fdcId: 173418, expectedDataType: "SR Legacy", exactUsdaDescription: "Cheese, cream" },
  { targetId: "protein_egg_whole_fried", fdcId: 173423, expectedDataType: "SR Legacy", exactUsdaDescription: "Egg, whole, cooked, fried" },
  { targetId: "protein_egg_whole_hard_boiled", fdcId: 173424, expectedDataType: "SR Legacy", exactUsdaDescription: "Egg, whole, cooked, hard-boiled" },
  { targetId: "fat_butter_unsalted", fdcId: 173430, expectedDataType: "SR Legacy", exactUsdaDescription: "Butter, without salt" },
  { targetId: "dairy_milk_1_percent", fdcId: 173441, expectedDataType: "SR Legacy", exactUsdaDescription: "Milk, fluid, 1% fat, without added vitamin A and vitamin D" },
  { targetId: "dairy_sour_cream_light", fdcId: 173443, expectedDataType: "SR Legacy", exactUsdaDescription: "Sour cream, light" },
  { targetId: "protein_chicken_drumstick_cooked", fdcId: 173612, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, broilers or fryers, drumstick, meat and skin, cooked, roasted" },
  { targetId: "protein_chicken_thigh_cooked_skin_on", fdcId: 173625, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, broilers or fryers, thigh, meat and skin, cooked, roasted" },
  { targetId: "protein_chicken_wing_cooked", fdcId: 173630, expectedDataType: "SR Legacy", exactUsdaDescription: "Chicken, broilers or fryers, wing, meat and skin, cooked, roasted" },
  { targetId: "seafood_salmon_atlantic_wild_raw", fdcId: 173686, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, salmon, Atlantic, wild, raw" },
  { targetId: "seafood_salmon_sockeye_raw", fdcId: 173691, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, salmon, sockeye, raw" },
  { targetId: "seafood_salmon_sockeye_cooked", fdcId: 173692, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, salmon, sockeye, cooked, dry heat" },
  { targetId: "grain_black_beans_cooked", fdcId: 173735, expectedDataType: "SR Legacy", exactUsdaDescription: "Beans, black, mature seeds, cooked, boiled, without salt" },
  { targetId: "grain_kidney_beans_cooked", fdcId: 173740, expectedDataType: "SR Legacy", exactUsdaDescription: "Beans, kidney, all types, mature seeds, cooked, boiled, without salt" },
  { targetId: "grain_chickpeas_cooked", fdcId: 173757, expectedDataType: "SR Legacy", exactUsdaDescription: "Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt" },
  { targetId: "fat_peanuts_dry_roasted", fdcId: 173806, expectedDataType: "SR Legacy", exactUsdaDescription: "Peanuts, all types, dry-roasted, without salt" },
  { targetId: "protein_ground_beef_85_cooked", fdcId: 174032, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, ground, 85% lean meat / 15% fat, patty, cooked, broiled" },
  { targetId: "protein_ground_beef_80_raw", fdcId: 174036, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, ground, 80% lean meat / 20% fat, raw" },
  { targetId: "protein_beef_sirloin_cooked", fdcId: 168633, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, top sirloin, steak, separable lean and fat, trimmed to 0\" fat, select, cooked, broiled" },
  { targetId: "seafood_halibut_cooked", fdcId: 174201, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, halibut, Atlantic and Pacific, cooked, dry heat" },
  { targetId: "seafood_crab_raw", fdcId: 174204, expectedDataType: "SR Legacy", exactUsdaDescription: "Crustaceans, crab, blue, raw" },
  { targetId: "seafood_crab_cooked", fdcId: 174205, expectedDataType: "SR Legacy", exactUsdaDescription: "Crustaceans, crab, blue, cooked, moist heat" },
  { targetId: "seafood_shrimp_raw", fdcId: 174210, expectedDataType: "SR Legacy", exactUsdaDescription: "Crustaceans, shrimp, mixed species, raw (may contain additives to retain moisture)" },
  { targetId: "seafood_pollock_cooked", fdcId: 174237, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, pollock, Atlantic, cooked, dry heat" },
  { targetId: "fat_peanut_butter", fdcId: 174294, expectedDataType: "SR Legacy", exactUsdaDescription: "Peanut Butter, smooth (Includes foods for USDA's Food Distribution Program)" },
  { targetId: "protein_ground_turkey_85_raw", fdcId: 174493, expectedDataType: "SR Legacy", exactUsdaDescription: "Turkey, ground, 85% lean, 15% fat, raw" },
  { targetId: "protein_ground_turkey_85_cooked", fdcId: 174494, expectedDataType: "SR Legacy", exactUsdaDescription: "Turkey, ground, 85% lean, 15% fat, pan-broiled crumbles" },
  { targetId: "fruit_grapes_raw", fdcId: 174683, expectedDataType: "SR Legacy", exactUsdaDescription: "Grapes, red or green (European type, such as Thompson seedless), raw" },
  { targetId: "protein_ground_beef_93_cooked", fdcId: 174752, expectedDataType: "SR Legacy", exactUsdaDescription: "Beef, ground, 93% lean meat / 7% fat, patty, cooked, broiled" },
  { targetId: "grain_bagel_plain", fdcId: 174899, expectedDataType: "SR Legacy", exactUsdaDescription: "Bagels, plain, enriched, with calcium propionate (includes onion, poppy, sesame)" },
  { targetId: "seafood_mackerel_cooked", fdcId: 175120, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, mackerel, Atlantic, cooked, dry heat" },
  { targetId: "seafood_sardines_canned_oil", fdcId: 175139, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, sardine, Atlantic, canned in oil, drained solids with bone" },
  { targetId: "seafood_tuna_yellowfin_raw", fdcId: 175159, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, tuna, fresh, yellowfin, raw" },
  { targetId: "seafood_salmon_atlantic_farmed_raw", fdcId: 175167, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, salmon, Atlantic, farmed, raw" },
  { targetId: "seafood_salmon_atlantic_farmed_cooked", fdcId: 175168, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, salmon, Atlantic, farmed, cooked, dry heat" },
  { targetId: "seafood_tilapia_raw", fdcId: 175176, expectedDataType: "SR Legacy", exactUsdaDescription: "Fish, tilapia, raw" },
  { targetId: "grain_pinto_beans_cooked", fdcId: 175200, expectedDataType: "SR Legacy", exactUsdaDescription: "Beans, pinto, mature seeds, cooked, boiled, without salt" },
  { targetId: "dairy_cheddar", fdcId: 170899, expectedDataType: "SR Legacy", exactUsdaDescription: "Cheese, cheddar, sharp, sliced" },
  { targetId: "dairy_yogurt_plain_lowfat", fdcId: 2705419, expectedDataType: "Survey (FNDDS)", exactUsdaDescription: "Yogurt, low fat milk, plain" },
  { targetId: "dairy_sour_cream_regular", fdcId: 2705614, expectedDataType: "Survey (FNDDS)", exactUsdaDescription: "Sour cream, regular" },
  { targetId: "protein_egg_white_cooked", fdcId: 2707169, expectedDataType: "Survey (FNDDS)", exactUsdaDescription: "Egg, white, cooked, NS as to fat" },
];

const expansionTargetById = new Map(CATALOG_DISCOVERY_TARGETS.map((target) => [target.id, target]));

function toExpansionManifestRecord(selection: ExpansionSelectionRecord): FoodCatalogManifestRecord {
  const target = expansionTargetById.get(selection.targetId);
  if (!target) {
    throw new Error(`Unknown expansion target id '${selection.targetId}' in manifest selections.`);
  }
  return {
    target: target.target,
    fdcId: selection.fdcId,
    displayName: target.target,
    exactUsdaDescription: selection.exactUsdaDescription,
    expectedDataType: selection.expectedDataType,
    category: target.category,
    aliases: target.suggestedAliases,
    preparationExpectation: target.preparationExpectation,
    notes: "Phase 2C reviewed batch selection.",
  };
}

const EXPANSION_REVIEWED_RECORDS = EXPANSION_SELECTIONS.map(toExpansionManifestRecord);

export const FOOD_CATALOG_PILOT_MANIFEST: FoodCatalogPilotManifest = {
  version: "food-catalog-pilot-manifest-v1",
  records: [...PILOT_LOCKED_RECORDS, ...EXPANSION_REVIEWED_RECORDS],
};
